export const ADD_REF_IMAGE = "ADD_REF_IMAGE";
export const REMOVE_REF_IMAGE = "REMOVE_REF_IMAGE";
export const ADD_QUERY_IMAGE = "ADD_QUERY_IMAGE";
export const REMOVE_QUERY_IMAGE = "REMOVE_QUERY_IMAGE";
export const NEXT_STEP = "NEXT_STEP";
export const PREVIOUS_STEP = "PREVIOUS_STEP";
export const UI_LOADING_START = "UI_LOADING_START";
export const UI_LOADING_END = "UI_LOADING_END";
